{% set name = "SQLObject" %}
{% set version = "3.7.0" %}
{% set sha256 = "c0d440b638c091027deea7330bb934188b86402cba552a0bbde0535ed8fdab93" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - formencode >=1.3.1
    - pydispatcher >=2.0.4

test:
  imports:
    - sqlobject
    - sqlobject.firebird
    - sqlobject.include
    - sqlobject.include.tests
    - sqlobject.inheritance
    - sqlobject.inheritance.tests
    - sqlobject.manager
    - sqlobject.maxdb
    - sqlobject.mssql
    - sqlobject.mysql
    - sqlobject.postgres
    - sqlobject.rdbhost
    - sqlobject.sqlite
    - sqlobject.sybase
    - sqlobject.tests
    - sqlobject.util
    - sqlobject.versioning
    - sqlobject.versioning.test

about:
  home: http://sqlobject.org/
  license: LGPL-2.1
  license_file: LICENSE
  summary: 'Object-Relational Manager, aka database wrapper'
  dev_url: https://github.com/sqlobject/sqlobject

extra:
  recipe-maintainers:
    - windelbouwmanbosch
    - windelbouwman
