travis:
  secure:
    BINSTAR_TOKEN: yCVsO/XSkEKWJrbBvyphnZcwwRNuBJZV+a91WSr3yiylZYFuUBU0ABdejsIo0rvOIAKDhv1r+mQ49dvCmAgtG5MsSCD4WgFLRTLjgYAy0snKibsPnVTyUFrn1yT7L5hG0ERnGPXROADikh0sCh7AI2feFKwvXN1nGRfDvr10PwdmVXp1qAmQOTheftrTGX2EVGkIlTknkR9XgetWCq/sgxEVyatd4+u5SvHW7r1POncJJpk8d3qZpD7+LTVMlKVgVxgn18OS9KiJo9rTz+PFt7hukT+XdIzYW40qHLQJulXZBYzcaGUfrmGdK/UNpEB+g3qb2cTrTpkTDQ8r5ZtSeFq1wjGG8WqbbG0YaR4EnUg/GcLUex10im1Gz9mkVrbCRh46CKYjAqDNojMGQJkpyh+4GjEgD5D8z8oYJNMJ3fiZlNMeSuygGCugtPR6U4xeGHyy2Kpae6yYSXVQiwcU0wD6S2Z4Xfni/iQ8oIWj5VZbuH8UWgkslYr461+cXPCAG/Yhl6g4rDIgR5d1scBQWZkQEwVrNy/6Nxu26EBC9mzPxmUwtxWGakFFPdNJChSFWfXiszQNUNUwaERzgEcJfyqS74gPMJCObXC43mGmCUt1KkmFGWf9KnPFIygxkmbwPCzqp3ZM8Wekd0lqks5dsH9aCzriJi8gdRRSlTe7QIU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
