travis:
  secure:
    BINSTAR_TOKEN: CvYvXUSMXNI2zyPt3vM0FlMnz7kKA+M/fCVv/BcnFwzFby4i3v+y8i9dcR51YZ29T0hW9h2WitZfHTN2m6WSswP6/I/6F3jbFVOXH570fXgVZolkYgQ02Jk7uFTWQICPalyzrWaQCv/T8rtu2ktkkrNHnxxw+KUj8o2a0qY9tAxxMFcGJqWBxzMm3QoTUuK3R0zFRwDbIONKGitMwFL9sO9tjurR3XbbNAWAR8uFtS4YH/K8Ig/9f9xkealTfoBym5OhkMNtbxM6uh7uWCP28Fk4M6pgLS60GFYe59ToRrlqL8IK3P/AsStrc89FKEn2p2Qxg+n6qM9J/uq33mA37d5CvoWitBGBSxYE9q/x6Wzm3awUIZF8U7I+XkqDy9cTKCTxjTVd1SqmjaMh5WsJC2iV6r67uIjxOK4xygGSluL81UAD3rFjoe5o5B2mN3QqNL2SP29LCP6YxVhVdRJmNfRhtfl8vlcLKjZYqGTokLAXLd8HQo5rOMnypWP+izgcrt3Gw6+7qUYMOgE1OWUEjwPnfBPCGUtizSPKWTvPtGyNMaPYx8RdOfDiAe9e7/drtSkN8jCnLDem431L/b8C5zT0OD12+pqMnVVfA213nTwCx4NAMD4Lo2UcpR/nsEJtHrPwSTYdmyj7XENiWKfMcWrsnNauaLb/exAQQfCChe8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
